//
// Ability.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Ability: Codable, JSONEncodable, Hashable {

    /** The identifier for this ability resource. */
    public var id: Int?
    /** The name for this ability resource. */
    public var name: String?
    /** Whether or not this ability originated in the main series of the video games. */
    public var isMainSeries: Bool?
    public var generation: AbilityGeneration?
    public var names: [AbilityNamesInner]?

    public init(id: Int? = nil, name: String? = nil, isMainSeries: Bool? = nil, generation: AbilityGeneration? = nil, names: [AbilityNamesInner]? = nil) {
        self.id = id
        self.name = name
        self.isMainSeries = isMainSeries
        self.generation = generation
        self.names = names
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case isMainSeries = "is_main_series"
        case generation
        case names
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(isMainSeries, forKey: .isMainSeries)
        try container.encodeIfPresent(generation, forKey: .generation)
        try container.encodeIfPresent(names, forKey: .names)
    }
}

