//
// AbilityEffectChange.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AbilityEffectChange: Codable, JSONEncodable, Hashable {

    public var effectEntries: [Effect]
    public var versionGroup: NamedAPIResource

    public init(effectEntries: [Effect], versionGroup: NamedAPIResource) {
        self.effectEntries = effectEntries
        self.versionGroup = versionGroup
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case effectEntries = "effect_entries"
        case versionGroup = "version_group"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(effectEntries, forKey: .effectEntries)
        try container.encode(versionGroup, forKey: .versionGroup)
    }
}

