//
// APIResource.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct APIResource: Codable, JSONEncodable, Hashable {

    /** The URL of the referenced resource. */
    public var url: String?
    /** The name of the referenced resource. */
    public var name: String?
    /** The ID of the referenced resource. */
    public var id: Int?

    public init(url: String? = nil, name: String? = nil, id: Int? = nil) {
        self.url = url
        self.name = name
        self.id = id
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case url
        case name
        case id
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(id, forKey: .id)
    }
}

