//
// BerryFlavorMap.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BerryFlavorMap: Codable, JSONEncodable, Hashable {

    /** How powerful the referenced flavor is for this berry */
    public var potency: Int
    public var flavor: BerryFlavor

    public init(potency: Int, flavor: BerryFlavor) {
        self.potency = potency
        self.flavor = flavor
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case potency
        case flavor
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(potency, forKey: .potency)
        try container.encode(flavor, forKey: .flavor)
    }
}

