//
// ContestComboDetail.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ContestComboDetail: Codable, JSONEncodable, Hashable {

    /** A list of moves to use before this move. */
    public var useBefore: [Move]?
    /** A list of moves to use after this move. */
    public var useAfter: [Move]?

    public init(useBefore: [Move]? = nil, useAfter: [Move]? = nil) {
        self.useBefore = useBefore
        self.useAfter = useAfter
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case useBefore = "use_before"
        case useAfter = "use_after"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(useBefore, forKey: .useBefore)
        try container.encodeIfPresent(useAfter, forKey: .useAfter)
    }
}

