//
// Description.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Description: Codable, JSONEncodable, Hashable {

    public var description: String?
    public var language: Language?

    public init(description: String? = nil, language: Language? = nil) {
        self.description = description
        self.language = language
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case description
        case language
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(language, forKey: .language)
    }
}

