//
// EffectEffect.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The various effects of the move &#x60;effect_entries&#x60; */
public struct EffectEffect: Codable, JSONEncodable, Hashable {

    /** The localized effect text of this effect */
    public var effect: String
    public var language: Language

    public init(effect: String, language: Language) {
        self.effect = effect
        self.language = language
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case effect
        case language
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(effect, forKey: .effect)
        try container.encode(language, forKey: .language)
    }
}

