//
// EncounterMethodRate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EncounterMethodRate: Codable, JSONEncodable, Hashable {

    public var encounterMethod: EncounterMethod?
    public var versionDetails: [EncounterVersionDetails]?

    public init(encounterMethod: EncounterMethod? = nil, versionDetails: [EncounterVersionDetails]? = nil) {
        self.encounterMethod = encounterMethod
        self.versionDetails = versionDetails
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case encounterMethod = "encounter_method"
        case versionDetails = "version_details"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(encounterMethod, forKey: .encounterMethod)
        try container.encodeIfPresent(versionDetails, forKey: .versionDetails)
    }
}

