//
// EncounterVersionDetails.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Version details of an encounter. */
public struct EncounterVersionDetails: Codable, JSONEncodable, Hashable {

    public var version: NamedAPIResource?
    /** The total percentage of all encounter potential. */
    public var maxChance: Int?
    /** A list of encounters and their specifics. */
    public var encounterDetails: [Encounter]?

    public init(version: NamedAPIResource? = nil, maxChance: Int? = nil, encounterDetails: [Encounter]? = nil) {
        self.version = version
        self.maxChance = maxChance
        self.encounterDetails = encounterDetails
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case version
        case maxChance = "max_chance"
        case encounterDetails = "encounter_details"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(version, forKey: .version)
        try container.encodeIfPresent(maxChance, forKey: .maxChance)
        try container.encodeIfPresent(encounterDetails, forKey: .encounterDetails)
    }
}

