//
// EncounterCondition.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EncounterCondition: Codable, JSONEncodable, Hashable {

    /** The identifier for this encounter condition resource */
    public var id: Int
    /** The name for this encounter condition resource */
    public var name: String
    /** A list of values that are used with this encounter condition */
    public var values: [NamedAPIResource]
    /** The name of this encounter condition listed in different languages */
    public var names: [Name]

    public init(id: Int, name: String, values: [NamedAPIResource], names: [Name]) {
        self.id = id
        self.name = name
        self.values = values
        self.names = names
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case values
        case names
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(values, forKey: .values)
        try container.encode(names, forKey: .names)
    }
}

