//
// EvolutionChain.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EvolutionChain: Codable, JSONEncodable, Hashable {

    /** The identifier for this evolution chain resource */
    public var id: Int
    public var babyTriggerItem: EvolutionChainBabyTriggerItem?
    public var chain: EvolutionChainChain

    public init(id: Int, babyTriggerItem: EvolutionChainBabyTriggerItem? = nil, chain: EvolutionChainChain) {
        self.id = id
        self.babyTriggerItem = babyTriggerItem
        self.chain = chain
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case babyTriggerItem = "baby_trigger_item"
        case chain
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(babyTriggerItem, forKey: .babyTriggerItem)
        try container.encode(chain, forKey: .chain)
    }
}

