//
// FlavorText.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct FlavorText: Codable, JSONEncodable, Hashable {

    public var flavorText: String?
    public var language: NamedAPIResource?
    public var version: NamedAPIResource?

    public init(flavorText: String? = nil, language: NamedAPIResource? = nil, version: NamedAPIResource? = nil) {
        self.flavorText = flavorText
        self.language = language
        self.version = version
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case flavorText = "flavor_text"
        case language
        case version
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(flavorText, forKey: .flavorText)
        try container.encodeIfPresent(language, forKey: .language)
        try container.encodeIfPresent(version, forKey: .version)
    }
}

