//
// Gender.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Gender: Codable, JSONEncodable, Hashable {

    /** The identifier for this gender resource */
    public var id: Int?
    /** The name for this gender resource */
    public var name: String?
    public var pokemonSpeciesDetails: [GenderPokemonSpeciesDetailsInner]?

    public init(id: Int? = nil, name: String? = nil, pokemonSpeciesDetails: [GenderPokemonSpeciesDetailsInner]? = nil) {
        self.id = id
        self.name = name
        self.pokemonSpeciesDetails = pokemonSpeciesDetails
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case pokemonSpeciesDetails = "pokemon_species_details"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(pokemonSpeciesDetails, forKey: .pokemonSpeciesDetails)
    }
}

