//
// GenerationGameIndex.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GenerationGameIndex: Codable, JSONEncodable, Hashable {

    /** The internal id of an API resource within game data. */
    public var gameIndex: Int?
    public var generation: Generation?

    public init(gameIndex: Int? = nil, generation: Generation? = nil) {
        self.gameIndex = gameIndex
        self.generation = generation
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case gameIndex = "game_index"
        case generation
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(gameIndex, forKey: .gameIndex)
        try container.encodeIfPresent(generation, forKey: .generation)
    }
}

