//
// GenerationAbilitiesInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GenerationAbilitiesInner: Codable, JSONEncodable, Hashable {

    /** The name of this ability */
    public var name: String?
    /** Whether or not this ability is a hidden one */
    public var isHidden: Bool?
    /** The slot this ability occupies in this Pokémon species */
    public var slot: Int?

    public init(name: String? = nil, isHidden: Bool? = nil, slot: Int? = nil) {
        self.name = name
        self.isHidden = isHidden
        self.slot = slot
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case isHidden = "is_hidden"
        case slot
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(isHidden, forKey: .isHidden)
        try container.encodeIfPresent(slot, forKey: .slot)
    }
}

