//
// Generation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Generation: Codable, JSONEncodable, Hashable {

    /** The identifier for this generation resource */
    public var id: Int?
    /** The name for this generation resource */
    public var name: String?
    public var abilities: [GenerationAbilitiesInner]?
    public var names: [GenerationNamesInner]?

    public init(id: Int? = nil, name: String? = nil, abilities: [GenerationAbilitiesInner]? = nil, names: [GenerationNamesInner]? = nil) {
        self.id = id
        self.name = name
        self.abilities = abilities
        self.names = names
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case abilities
        case names
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(abilities, forKey: .abilities)
        try container.encodeIfPresent(names, forKey: .names)
    }
}

