//
// Genus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Genus: Codable, JSONEncodable, Hashable {

    public var genus: String?
    public var language: Language?

    public init(genus: String? = nil, language: Language? = nil) {
        self.genus = genus
        self.language = language
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case genus
        case language
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(genus, forKey: .genus)
        try container.encodeIfPresent(language, forKey: .language)
    }
}

