//
// GrowthRate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GrowthRate: Codable, JSONEncodable, Hashable {

    /** The identifier for this growth rate resource */
    public var id: Int?
    /** The name for this growth rate resource */
    public var name: String?
    /** The formula used to calculate the rate at which the Pokémon species gains level */
    public var formula: String?
    /** The description of this growth rate listed in different languages */
    public var descriptions: [Description]?

    public init(id: Int? = nil, name: String? = nil, formula: String? = nil, descriptions: [Description]? = nil) {
        self.id = id
        self.name = name
        self.formula = formula
        self.descriptions = descriptions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case formula
        case descriptions
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(formula, forKey: .formula)
        try container.encodeIfPresent(descriptions, forKey: .descriptions)
    }
}

