//
// ItemFlingEffect.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ItemFlingEffect: Codable, JSONEncodable, Hashable {

    public var id: Int?
    public var name: String?
    public var effectEntries: [VerboseEffect]?
    public var items: [Item]?

    public init(id: Int? = nil, name: String? = nil, effectEntries: [VerboseEffect]? = nil, items: [Item]? = nil) {
        self.id = id
        self.name = name
        self.effectEntries = effectEntries
        self.items = items
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case effectEntries = "effect_entries"
        case items
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(effectEntries, forKey: .effectEntries)
        try container.encodeIfPresent(items, forKey: .items)
    }
}

