//
// ItemPocket.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ItemPocket: Codable, JSONEncodable, Hashable {

    public var id: Int?
    public var name: String?
    public var categories: [ItemCategory]?

    public init(id: Int? = nil, name: String? = nil, categories: [ItemCategory]? = nil) {
        self.id = id
        self.name = name
        self.categories = categories
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case categories
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(categories, forKey: .categories)
    }
}

