//
// Language.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Language: Codable, JSONEncodable, Hashable {

    public var id: Int?
    public var name: String?
    public var official: Bool?
    public var iso639: String?
    public var iso3166: String?
    public var names: [Name]?

    public init(id: Int? = nil, name: String? = nil, official: Bool? = nil, iso639: String? = nil, iso3166: String? = nil, names: [Name]? = nil) {
        self.id = id
        self.name = name
        self.official = official
        self.iso639 = iso639
        self.iso3166 = iso3166
        self.names = names
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case official
        case iso639
        case iso3166
        case names
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(official, forKey: .official)
        try container.encodeIfPresent(iso639, forKey: .iso639)
        try container.encodeIfPresent(iso3166, forKey: .iso3166)
        try container.encodeIfPresent(names, forKey: .names)
    }
}

