//
// Location.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Location: Codable, JSONEncodable, Hashable {

    public var id: Int?
    public var name: String?
    public var region: NamedAPIResource?
    public var names: [Name]?
    public var gameIndices: [GenerationGameIndex]?
    public var areas: [NamedAPIResource]?

    public init(id: Int? = nil, name: String? = nil, region: NamedAPIResource? = nil, names: [Name]? = nil, gameIndices: [GenerationGameIndex]? = nil, areas: [NamedAPIResource]? = nil) {
        self.id = id
        self.name = name
        self.region = region
        self.names = names
        self.gameIndices = gameIndices
        self.areas = areas
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case region
        case names
        case gameIndices = "game_indices"
        case areas
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(region, forKey: .region)
        try container.encodeIfPresent(names, forKey: .names)
        try container.encodeIfPresent(gameIndices, forKey: .gameIndices)
        try container.encodeIfPresent(areas, forKey: .areas)
    }
}

