//
// Machine.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Machine: Codable, JSONEncodable, Hashable {

    public var id: Int?
    public var item: NamedAPIResource?
    public var move: NamedAPIResource?
    public var versionGroup: NamedAPIResource?

    public init(id: Int? = nil, item: NamedAPIResource? = nil, move: NamedAPIResource? = nil, versionGroup: NamedAPIResource? = nil) {
        self.id = id
        self.item = item
        self.move = move
        self.versionGroup = versionGroup
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case item
        case move
        case versionGroup = "version_group"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(item, forKey: .item)
        try container.encodeIfPresent(move, forKey: .move)
        try container.encodeIfPresent(versionGroup, forKey: .versionGroup)
    }
}

