//
// MoveLearnMethod.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Methods by which Pokémon can learn moves. */
public struct MoveLearnMethod: Codable, JSONEncodable, Hashable {

    /** The identifier for this move learn method resource. */
    public var id: Int
    /** The name for this move learn method resource. */
    public var name: String
    /** The description of this move learn method listed in different languages. */
    public var descriptions: [Description]?
    /** The name of this move learn method listed in different languages. */
    public var names: [Name]?

    public init(id: Int, name: String, descriptions: [Description]? = nil, names: [Name]? = nil) {
        self.id = id
        self.name = name
        self.descriptions = descriptions
        self.names = names
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case descriptions
        case names
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(descriptions, forKey: .descriptions)
        try container.encodeIfPresent(names, forKey: .names)
    }
}

