//
// MoveDamageClass.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MoveDamageClass: Codable, JSONEncodable, Hashable {

    public var id: Int
    public var name: String
    public var descriptions: [Description]

    public init(id: Int, name: String, descriptions: [Description]) {
        self.id = id
        self.name = name
        self.descriptions = descriptions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case descriptions
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(descriptions, forKey: .descriptions)
    }
}

