//
// MoveAilment.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MoveAilment: Codable, JSONEncodable, Hashable {

    public var id: Int
    public var name: String
    public var moves: [Move]

    public init(id: Int, name: String, moves: [Move]) {
        self.id = id
        self.name = name
        self.moves = moves
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case moves
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(moves, forKey: .moves)
    }
}

