//
// MoveStatAffect.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MoveStatAffect: Codable, JSONEncodable, Hashable {

    /** The amount of change to the referenced stat. */
    public var change: Int
    public var move: NamedAPIResource

    public init(change: Int, move: NamedAPIResource) {
        self.change = change
        self.move = move
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case change
        case move
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(change, forKey: .change)
        try container.encode(move, forKey: .move)
    }
}

