//
// NatureStatAffect.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct NatureStatAffect: Codable, JSONEncodable, Hashable {

    public var increase: [Nature]?
    public var decrease: [Nature]?

    public init(increase: [Nature]? = nil, decrease: [Nature]? = nil) {
        self.increase = increase
        self.decrease = decrease
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case increase
        case decrease
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(increase, forKey: .increase)
        try container.encodeIfPresent(decrease, forKey: .decrease)
    }
}

