//
// PalParkEncounterArea.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Areas where the Pokémon species can be encountered in pal park. */
public struct PalParkEncounterArea: Codable, JSONEncodable, Hashable {

    /** The base score given to the player when the referenced Pokemon is caught during a pal park run. */
    public var baseScore: Int?
    /** The base rate for encountering the referenced Pokemon in this pal park area. */
    public var rate: Int?
    public var area: NamedAPIResource?

    public init(baseScore: Int? = nil, rate: Int? = nil, area: NamedAPIResource? = nil) {
        self.baseScore = baseScore
        self.rate = rate
        self.area = area
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case baseScore = "base_score"
        case rate
        case area
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(baseScore, forKey: .baseScore)
        try container.encodeIfPresent(rate, forKey: .rate)
        try container.encodeIfPresent(area, forKey: .area)
    }
}

