//
// PastMoveStatValuesEffectEntriesInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PastMoveStatValuesEffectEntriesInner: Codable, JSONEncodable, Hashable {

    public var effect: VerboseEffect?
    public var versionGroup: NamedAPIResource?

    public init(effect: VerboseEffect? = nil, versionGroup: NamedAPIResource? = nil) {
        self.effect = effect
        self.versionGroup = versionGroup
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case effect
        case versionGroup = "version_group"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(effect, forKey: .effect)
        try container.encodeIfPresent(versionGroup, forKey: .versionGroup)
    }
}

