//
// PokeathlonStatAffectingNatures.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A detail of natures which affect this Pokéathlon stat positively or negatively */
public struct PokeathlonStatAffectingNatures: Codable, JSONEncodable, Hashable {

    /** A list of natures that positively affect this Pokéathlon stat */
    public var increase: [NaturePokeathlonStatAffectSets]?
    /** A list of natures that negatively affect this Pokéathlon stat */
    public var decrease: [NaturePokeathlonStatAffectSets]?

    public init(increase: [NaturePokeathlonStatAffectSets]? = nil, decrease: [NaturePokeathlonStatAffectSets]? = nil) {
        self.increase = increase
        self.decrease = decrease
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case increase
        case decrease
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(increase, forKey: .increase)
        try container.encodeIfPresent(decrease, forKey: .decrease)
    }
}

