//
// PokemonSpeciesVariety.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PokemonSpeciesVariety: Codable, JSONEncodable, Hashable {

    /** Whether this is the default \"natural\" variety of this species. Note that \"default\" is subjective and that it may not match the Pokémon games' official status.  */
    public var isDefault: Bool?
    public var pokemon: Pokemon?
    /** The name of this Pokémon species variety */
    public var name: String?

    public init(isDefault: Bool? = nil, pokemon: Pokemon? = nil, name: String? = nil) {
        self.isDefault = isDefault
        self.pokemon = pokemon
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case isDefault = "is_default"
        case pokemon
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(isDefault, forKey: .isDefault)
        try container.encodeIfPresent(pokemon, forKey: .pokemon)
        try container.encodeIfPresent(name, forKey: .name)
    }
}

