//
// PokemonHabitatList200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PokemonHabitatList200Response: Codable, JSONEncodable, Hashable {

    /** The total number of pokemon habitats. */
    public var count: Int?
    /** URL to retrieve the next page of pokemon habitats. */
    public var next: String?
    /** URL to retrieve the previous page of pokemon habitats. */
    public var previous: String?
    public var results: [PokemonHabitat]?

    public init(count: Int? = nil, next: String? = nil, previous: String? = nil, results: [PokemonHabitat]? = nil) {
        self.count = count
        self.next = next
        self.previous = previous
        self.results = results
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case count
        case next
        case previous
        case results
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(count, forKey: .count)
        try container.encodeIfPresent(next, forKey: .next)
        try container.encodeIfPresent(previous, forKey: .previous)
        try container.encodeIfPresent(results, forKey: .results)
    }
}

