//
// PokemonMove.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PokemonMove: Codable, JSONEncodable, Hashable {

    public var move: NamedAPIResource?
    /** A list of details showing how the Pokémon can learn the move  */
    public var versionGroupDetails: [PokemonMoveVersionGroupDetailsInner]?

    public init(move: NamedAPIResource? = nil, versionGroupDetails: [PokemonMoveVersionGroupDetailsInner]? = nil) {
        self.move = move
        self.versionGroupDetails = versionGroupDetails
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case move
        case versionGroupDetails = "version_group_details"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(move, forKey: .move)
        try container.encodeIfPresent(versionGroupDetails, forKey: .versionGroupDetails)
    }
}

