//
// PokemonStat.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PokemonStat: Codable, JSONEncodable, Hashable {

    public var stat: NamedAPIResource?
    /** The effort points (EV) the Pokémon has in the stat. */
    public var effort: Int?
    /** The base value of the stat. */
    public var baseStat: Int?

    public init(stat: NamedAPIResource? = nil, effort: Int? = nil, baseStat: Int? = nil) {
        self.stat = stat
        self.effort = effort
        self.baseStat = baseStat
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case stat
        case effort
        case baseStat = "base_stat"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(stat, forKey: .stat)
        try container.encodeIfPresent(effort, forKey: .effort)
        try container.encodeIfPresent(baseStat, forKey: .baseStat)
    }
}

