//
// PokeathlonStat.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PokeathlonStat: Codable, JSONEncodable, Hashable {

    /** The identifier for this Pokéathlon stat resource */
    public var id: Int
    /** The name for this Pokéathlon stat resource */
    public var name: String
    /** The name of this Pokéathlon stat listed in different languages */
    public var names: [Name]
    public var affectingNatures: PokeathlonStatAffectingNatures

    public init(id: Int, name: String, names: [Name], affectingNatures: PokeathlonStatAffectingNatures) {
        self.id = id
        self.name = name
        self.names = names
        self.affectingNatures = affectingNatures
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case names
        case affectingNatures = "affecting_natures"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(names, forKey: .names)
        try container.encode(affectingNatures, forKey: .affectingNatures)
    }
}

