//
// Pokedex.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Pokedex: Codable, JSONEncodable, Hashable {

    public var id: Int
    public var name: String
    public var isMainSeries: Bool
    public var descriptions: [Description]
    public var pokemonEntries: [PokemonEntry]
    public var region: NamedAPIResource

    public init(id: Int, name: String, isMainSeries: Bool, descriptions: [Description], pokemonEntries: [PokemonEntry], region: NamedAPIResource) {
        self.id = id
        self.name = name
        self.isMainSeries = isMainSeries
        self.descriptions = descriptions
        self.pokemonEntries = pokemonEntries
        self.region = region
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case isMainSeries = "is_main_series"
        case descriptions
        case pokemonEntries = "pokemon_entries"
        case region
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(isMainSeries, forKey: .isMainSeries)
        try container.encode(descriptions, forKey: .descriptions)
        try container.encode(pokemonEntries, forKey: .pokemonEntries)
        try container.encode(region, forKey: .region)
    }
}

