//
// PokemonEncounter.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Encounters Pokemon that can be encountered in the game and the version groups in which they can be encountered. */
public struct PokemonEncounter: Codable, JSONEncodable, Hashable {

    public var pokemon: NamedAPIResource?
    public var versionDetails: [EncounterVersionDetails]?

    public init(pokemon: NamedAPIResource? = nil, versionDetails: [EncounterVersionDetails]? = nil) {
        self.pokemon = pokemon
        self.versionDetails = versionDetails
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pokemon
        case versionDetails = "version_details"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(pokemon, forKey: .pokemon)
        try container.encodeIfPresent(versionDetails, forKey: .versionDetails)
    }
}

