//
// PokemonType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PokemonType: Codable, JSONEncodable, Hashable {

    /** The order the Pokémon's types are listed in. */
    public var slot: Int?
    public var type: NamedAPIResource?

    public init(slot: Int? = nil, type: NamedAPIResource? = nil) {
        self.slot = slot
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case slot
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(slot, forKey: .slot)
        try container.encodeIfPresent(type, forKey: .type)
    }
}

