//
// PokeathlonStatAffect.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PokeathlonStatAffect: Codable, JSONEncodable, Hashable {

    /** The maximum amount of change to the referenced Pokéathlon stat. */
    public var maxChange: Int
    public var nature: Nature

    public init(maxChange: Int, nature: Nature) {
        self.maxChange = maxChange
        self.nature = nature
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case maxChange = "max_change"
        case nature
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(maxChange, forKey: .maxChange)
        try container.encode(nature, forKey: .nature)
    }
}

