//
// PokemonAbility.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PokemonAbility: Codable, JSONEncodable, Hashable {

    public var isHidden: Bool?
    public var slot: Int?
    public var ability: Ability?

    public init(isHidden: Bool? = nil, slot: Int? = nil, ability: Ability? = nil) {
        self.isHidden = isHidden
        self.slot = slot
        self.ability = ability
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case isHidden = "is_hidden"
        case slot
        case ability
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(isHidden, forKey: .isHidden)
        try container.encodeIfPresent(slot, forKey: .slot)
        try container.encodeIfPresent(ability, forKey: .ability)
    }
}

