//
// PokeathlonStatName.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PokeathlonStatName: Codable, JSONEncodable, Hashable {

    public var name: String?
    public var names: [Name]?

    public init(name: String? = nil, names: [Name]? = nil) {
        self.name = name
        self.names = names
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case names
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(names, forKey: .names)
    }
}

