//
// PokemonHeldItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PokemonHeldItem: Codable, JSONEncodable, Hashable {

    public var item: Item?
    public var versionDetails: [PokemonHeldItemVersionDetailsInner]?

    public init(item: Item? = nil, versionDetails: [PokemonHeldItemVersionDetailsInner]? = nil) {
        self.item = item
        self.versionDetails = versionDetails
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case item
        case versionDetails = "version_details"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(item, forKey: .item)
        try container.encodeIfPresent(versionDetails, forKey: .versionDetails)
    }
}

