//
// PokemonEntry.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PokemonEntry: Codable, JSONEncodable, Hashable {

    /** The index number within the Pokédex. */
    public var entryNumber: Int?
    public var pokemonSpecies: NamedAPIResource?

    public init(entryNumber: Int? = nil, pokemonSpecies: NamedAPIResource? = nil) {
        self.entryNumber = entryNumber
        self.pokemonSpecies = pokemonSpecies
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case entryNumber = "entry_number"
        case pokemonSpecies = "pokemon_species"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(entryNumber, forKey: .entryNumber)
        try container.encodeIfPresent(pokemonSpecies, forKey: .pokemonSpecies)
    }
}

