//
// SuperContestEffect.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SuperContestEffect: Codable, JSONEncodable, Hashable {

    public var id: Int
    public var appeal: Int
    public var flavorTextEntries: [FlavorText]
    public var moves: [NamedAPIResource]

    public init(id: Int, appeal: Int, flavorTextEntries: [FlavorText], moves: [NamedAPIResource]) {
        self.id = id
        self.appeal = appeal
        self.flavorTextEntries = flavorTextEntries
        self.moves = moves
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case appeal
        case flavorTextEntries = "flavor_text_entries"
        case moves
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(appeal, forKey: .appeal)
        try container.encode(flavorTextEntries, forKey: .flavorTextEntries)
        try container.encode(moves, forKey: .moves)
    }
}

