//
// VerboseEffect.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct VerboseEffect: Codable, JSONEncodable, Hashable {

    /** The localized effect text for an API resource in a specific language. */
    public var effect: String?

    public init(effect: String? = nil) {
        self.effect = effect
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case effect
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(effect, forKey: .effect)
    }
}

