//
// VersionGameIndex.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct VersionGameIndex: Codable, JSONEncodable, Hashable {

    /** The internal id of the game used in generation VI and VII to identify different versions of the same Pokémon species.  */
    public var gameIndex: Int?
    public var version: NamedAPIResource?

    public init(gameIndex: Int? = nil, version: NamedAPIResource? = nil) {
        self.gameIndex = gameIndex
        self.version = version
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case gameIndex = "game_index"
        case version
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(gameIndex, forKey: .gameIndex)
        try container.encodeIfPresent(version, forKey: .version)
    }
}

